# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mPGYmk_FHuvoBn79i_Rc85Eksm6bHH5h
"""

# -*- coding: utf-8 -*-
import os
import math
import pandas as pd
import psspy

# =========================================================
# 0. QUIET / LOGGING CONTROLS
# =========================================================
VERBOSE = False                  # False = no hourly console prints
SAVE_ACCOR_TEXT_LOGS = True      # True = keep ACCOR text logs
SHOW_FINAL_MESSAGE = True        # True = show only final completion message

def vprint(*args, **kwargs):
    if VERBOSE:
        print(*args, **kwargs)

def final_print(*args, **kwargs):
    if SHOW_FINAL_MESSAGE:
        print(*args, **kwargs)

def mute_psse_output():
    """
    Disable PSSE console/screen output.
    ISLCT=6 -> no output device
    """
    psspy.report_output(6, "", [])
    psspy.progress_output(6, "", [])
    psspy.alert_output(6, "", [])
    psspy.prompt_output(6, "", [])

def route_psse_output_to_files(logs):
    """
    Send PSSE output to text files instead of console.
    ISLCT=2 -> output to file
    """
    psspy.report_output(2, logs["report"], [0, 0])
    psspy.progress_output(2, logs["progress"], [0, 0])
    psspy.alert_output(2, logs["alert"], [0, 0])
    psspy.prompt_output(2, logs["prompt"], [0, 0])

# =========================================================
# 1. INITIALIZATION
# =========================================================
psspy.psseinit(200000)

# keep PSSE console quiet from the beginning
mute_psse_output()
psspy.lines_per_page_one_device(1, 1000000)

PROJECT_PATH = r"C:\Users\tanbir.rahman\Documents\PTI\PSSE35\EXAMPLE\Projects"
os.chdir(PROJECT_PATH)

BASE_CASE = os.path.join(PROJECT_PATH, "2021RC_2025SP_South-High_Tie-Econ_Solar-0.95_p.sav")
LOAD_CSV  = os.path.join(PROJECT_PATH, "load_clean.csv")
GEN_CSV   = os.path.join(PROJECT_PATH, "gen_clean.csv")
GEN_MAP   = os.path.join(PROJECT_PATH, "gen_map_clean.csv")

SUB_FILE  = os.path.join(PROJECT_PATH, "study.sub")
MON_FILE  = os.path.join(PROJECT_PATH, "study.mon")
CON_FILE  = os.path.join(PROJECT_PATH, "study.con")
DFX_FILE  = os.path.join(PROJECT_PATH, "brooks_area.dfx")

# =========================================================
# 2. SETTINGS
# =========================================================
STUDY_HOURS = 8760       # set lower for testing if needed
V_MIN = 0.95
V_MAX = 1.05
THERMAL_LIMIT = 100.0

# Must exactly match subsystem label in study.sub
GEN_CTRL_LABEL = "ALL_ALBERTA"

# ---------------------------------------------------------
# OLD ACCOR API
# OPTIONS(10), VALUES(7), LABELS(3)
# ---------------------------------------------------------
ACCOR_OPTIONS = [
    0,  # 1 tap adjustment flag
    0,  # 2 area interchange adjustment flag
    0,  # 3 phase shift adjustment flag
    0,  # 4 dc tap adjustment flag
    0,  # 5 switched shunt adjustment flag
    1,  # 6 rating set: 1 = Rating A
    1,  # 7 number of power flow solutions
    1,  # 8 generator control flag
    0,  # 9 load control flag
    0   # 10 phase shifter control flag
]

ACCOR_VALUES = [
    200,    # 1 MW mismatch tolerance
    100.0,  # 2 percent of rating set
    0.1,    # 3 bus voltage violation tolerance
    0.1,    # 4 branch flow overload tolerance
    1.0,    # 5 generator control weighting factor
    1.0,    # 6 load control weighting factor
    1.0     # 7 phase shifter control weighting factor
]

ACCOR_LABELS = [
    GEN_CTRL_LABEL,  # 1 generator control subsystem
    "",              # 2 load control subsystem
    ""               # 3 phase shifter control subsystem
]

# =========================================================
# 3. LOGGING / DEBUG HELPERS
# =========================================================
def accor_ierr_text(ierr):
    mapping = {
        0:  "no error occurred",
        1:  "invalid OPTIONS value",
        2:  "invalid VALUES value",
        3:  "generators are converted",
        4:  "buses in island(s) without a swing bus; use TREE",
        5:  "No controls",
        6:  "control subsystem not defined",
        7:  "Distribution Factor Data File not specified",
        8:  "largest mismatch exceeds tolerance",
        21: "DFX file is not a valid DFAX file; run DFAX",
        22: "monitored elements exceed limit when adding multi-section line members",
        51: "error opening Distribution Factor Data File",
        52: "prerequisite requirements for API are not met"
    }
    return mapping.get(ierr, "unknown ierr")

def build_log_paths(t):
    stamp = pd.Timestamp(t).strftime("%Y%m%d_%H%M")
    return {
        "report":   os.path.join(PROJECT_PATH, f"accor_report_{stamp}.txt"),
        "progress": os.path.join(PROJECT_PATH, f"accor_progress_{stamp}.txt"),
        "alert":    os.path.join(PROJECT_PATH, f"accor_alert_{stamp}.txt"),
        "prompt":   os.path.join(PROJECT_PATH, f"accor_prompt_{stamp}.txt"),
        "summary":  os.path.join(PROJECT_PATH, f"accor_debug_summary_{stamp}.txt"),
    }

def start_psse_logging(logs):
    if SAVE_ACCOR_TEXT_LOGS:
        route_psse_output_to_files(logs)
    else:
        mute_psse_output()

def stop_psse_logging():
    # always mute console again after DFAX/ACCOR stage
    mute_psse_output()

def write_debug_summary(
    summary_file,
    t,
    dfax_ierr,
    accor_ierr,
    thermal_pre_count,
    voltage_pre_count,
    thermal_post_count,
    voltage_post_count,
    generators_changed,
    solve_mode_pre,
    solve_mode_post
):
    with open(summary_file, "w") as f:
        f.write(f"time = {pd.Timestamp(t)}\n")
        f.write(f"CON_FILE = {CON_FILE}\n")
        f.write(f"SUB_FILE = {SUB_FILE}\n")
        f.write(f"MON_FILE = {MON_FILE}\n")
        f.write(f"DFX_FILE = {DFX_FILE}\n")
        f.write(f"GEN_CTRL_LABEL = {GEN_CTRL_LABEL}\n")
        f.write("\n")
        f.write(f"dfax_ierr = {dfax_ierr}\n")
        f.write(f"accor_ierr = {accor_ierr}\n")
        f.write(f"accor_ierr_text = {accor_ierr_text(accor_ierr)}\n")
        f.write("\n")
        f.write(f"ACCOR_OPTIONS = {ACCOR_OPTIONS}\n")
        f.write(f"ACCOR_VALUES  = {ACCOR_VALUES}\n")
        f.write(f"ACCOR_LABELS  = {ACCOR_LABELS}\n")
        f.write("\n")
        f.write(f"solve_mode_pre = {solve_mode_pre}\n")
        f.write(f"solve_mode_post = {solve_mode_post}\n")
        f.write(f"thermal_pre_count = {thermal_pre_count}\n")
        f.write(f"voltage_pre_count = {voltage_pre_count}\n")
        f.write(f"thermal_post_count = {thermal_post_count}\n")
        f.write(f"voltage_post_count = {voltage_post_count}\n")
        f.write(f"generators_changed = {generators_changed}\n")

# =========================================================
# 4. GENERAL HELPERS
# =========================================================
def save_csv(records, path, columns):
    df = pd.DataFrame(records)

    if df.empty:
        df = pd.DataFrame(columns=columns)
    else:
        for c in columns:
            if c not in df.columns:
                df[c] = None
        df = df[columns]

    if "time" in df.columns and not df.empty:
        df["time"] = pd.to_datetime(df["time"]).dt.strftime("%Y-%m-%d %H:%M:%S")

    try:
        df.to_csv(path, index=False)
    except PermissionError:
        alt_path = path.replace(".csv", "_new.csv")
        df.to_csv(alt_path, index=False)

def fmt_id(raw_id):
    return str(raw_id).strip().ljust(2)

def solve_case():
    """
    Try several solve methods.
    Returns:
        solved (bool), solve_mode (str)
    """
    try:
        ierr = psspy.fnsl([1, 0, 0, 1, 1, 0, 99, 0])   # flat-start NR
        if ierr == 0 and psspy.solved() == 0:
            return True, "flat_start_nr"
    except:
        pass

    try:
        ierr = psspy.fnsl([0, 0, 0, 1, 1, 0, 99, 0])   # normal NR
        if ierr == 0 and psspy.solved() == 0:
            return True, "normal_nr"
    except:
        pass

    try:
        ierr = psspy.mslv()                            # fallback
        if ierr == 0 and psspy.solved() == 0:
            return True, "mslv"
    except:
        pass

    try:
        ierr = psspy.fnsl([0, 0, 0, 1, 1, 1, 99, 0])  # final retry
        if ierr == 0 and psspy.solved() == 0:
            return True, "nr_after_mslv"
    except:
        pass

    return False, "failed"

def machine_snapshot():
    """
    Snapshot all machine PGEN values.
    Returns dict like: {"12345_1": pgen, ...}
    """
    ierr1, bus = psspy.amachint(-1, 4, "NUMBER")
    ierr2, mid = psspy.amachchar(-1, 4, "ID")
    ierr3, pgen = psspy.amachreal(-1, 4, "PGEN")

    snap = {}
    if ierr1 == 0 and ierr2 == 0 and ierr3 == 0:
        for b, i, p in zip(bus[0], mid[0], pgen[0]):
            snap["{}_{}".format(b, i.strip())] = p
    return snap

def get_machine_name_map():
    out = {}
    try:
        gm = pd.read_csv(GEN_MAP)
        needed = {"bus", "id", "asset_group"}
        if needed.issubset(set(gm.columns)):
            for _, r in gm.iterrows():
                key = "{}_{}".format(int(r["bus"]), str(r["id"]).strip())
                out[key] = str(r["asset_group"]).strip()
    except:
        pass
    return out

# =========================================================
# 5. LOAD DATA
# =========================================================
def load_data():
    ld = pd.read_csv(LOAD_CSV)
    gd = pd.read_csv(GEN_CSV)
    gm = pd.read_csv(GEN_MAP)

    ld.rename(columns={
        "DT_MST": "datetime",
        "Bus Number": "bus",
        "Id": "id",
        "P_MW": "p_mw",
        "Q_Mvar": "q_mvar"
    }, inplace=True)

    gd.rename(columns={
        "DT_MST": "datetime",
        "MW": "mw"
    }, inplace=True)

    ld["datetime"] = pd.to_datetime(ld["datetime"]).dt.floor("H")
    gd["datetime"] = pd.to_datetime(gd["datetime"]).dt.floor("H")

    gm["asset_group"] = gm["asset_group"].astype(str).str.upper().str.strip()
    gd["asset_group"] = gd["asset_group"].astype(str).str.upper().str.strip()

    return ld, gd, gm

# =========================================================
# 6. APPLY DISPATCH
# =========================================================
def apply_dispatch(t, ld, gd, gm):
    # -------------------------
    # LOAD
    # -------------------------
    hr_ld = ld[ld["datetime"] == t]
    for _, r in hr_ld.iterrows():
        psspy.load_chng_5(
            int(r["bus"]),
            fmt_id(r["id"]),
            realar1=float(r["p_mw"]),
            realar2=float(r["q_mvar"])
        )

    # -------------------------
    # GENERATION
    # simple equal-share logic
    # -------------------------
    hr_gn = gd[gd["datetime"] == t]
    for _, r in hr_gn.iterrows():
        mw = float(r["mw"])
        if mw <= 0.01:
            continue

        asset = str(r["asset_group"]).upper().strip()
        units = gm[gm["asset_group"] == asset]

        if not units.empty:
            share = mw / len(units)
            for _, u in units.iterrows():
                psspy.machine_chng_2(
                    int(u["bus"]),
                    fmt_id(u["id"]),
                    realar1=share
                )

# =========================================================
# 7. METRICS
# =========================================================
def get_metrics():
    thermal = []
    voltage = []
    max_loading = 0.0

    ierr1, data = psspy.abrnreal(-1, 0, 0, 1, 1, ["P", "Q", "RATEA"])
    ierr2, ids = psspy.abrnchar(-1, 0, 0, 1, 1, ["ID"])
    ierr3, buses = psspy.abrnint(-1, 0, 0, 1, 1, ["FROMNUMBER", "TONUMBER"])

    if ierr1 == 0 and ierr2 == 0 and ierr3 == 0:
        for fb, tb, ck, p, q, rate in zip(
            buses[0], buses[1], ids[0], data[0], data[1], data[2]
        ):
            mva = math.sqrt(p**2 + q**2)
            pct = (mva / rate) * 100.0 if rate > 0 else 0.0
            max_loading = max(max_loading, pct)

            if pct > THERMAL_LIMIT:
                thermal.append({
                    "branch": "{}-{}".format(fb, tb),
                    "ckt": ck.strip(),
                    "pct": round(pct, 2)
                })

    ierr4, b = psspy.abusint(-1, 2, "NUMBER")
    ierr5, v = psspy.abusreal(-1, 2, "PU")

    if ierr4 == 0 and ierr5 == 0:
        for bus, pu in zip(b[0], v[0]):
            if pu < V_MIN or pu > V_MAX:
                voltage.append({
                    "bus": bus,
                    "pu": round(pu, 4)
                })

    return max_loading, thermal, voltage

# =========================================================
# 8. ACCOR RUNNER
# =========================================================
def run_accor(t):
    """
    Build DFAX and run old ACCOR with text logs saved to file,
    while keeping PSSE console muted.
    Returns:
        success (bool), stage (str), ierr_code (int), logs (dict), dfax_ierr (int)
    """
    logs = build_log_paths(t)

    # Start routing PSSE output to files before DFAX/ACCOR
    # so console remains silent and text logs are preserved.
    start_psse_logging(logs)
    try:
        ierr_dfax = psspy.dfax_2([1, 1, 0], SUB_FILE, MON_FILE, CON_FILE, DFX_FILE)
        if ierr_dfax != 0:
            return False, "dfax_failed", ierr_dfax, logs, ierr_dfax

        ierr_accor = psspy.accor(ACCOR_OPTIONS, ACCOR_VALUES, ACCOR_LABELS, DFX_FILE)
        if ierr_accor != 0:
            return False, "accor_failed", ierr_accor, logs, ierr_dfax

    finally:
        stop_psse_logging()

    return True, "accor_ok", 0, logs, ierr_dfax

# =========================================================
# 9. MAIN
# =========================================================
def main():
    ld, gd, gm = load_data()
    times = sorted(gd["datetime"].unique())[:STUDY_HOURS]

    gen_name_map = get_machine_name_map()

    n0_summary = []
    post_accor_summary = []
    thermal_pre_all = []
    voltage_pre_all = []
    thermal_post_all = []
    voltage_post_all = []
    curtailment = []
    accor_debug = []
    hour_status = []

    for t in times:
        ierr_case = psspy.case(BASE_CASE)
        if ierr_case != 0:
            hour_status.append({
                "time": t,
                "status": "case_load_failed",
                "detail": "case ierr={}".format(ierr_case)
            })
            continue

        try:
            apply_dispatch(t, ld, gd, gm)
        except Exception as e:
            hour_status.append({
                "time": t,
                "status": "dispatch_failed",
                "detail": str(e)
            })
            continue

        solved, solve_mode_pre = solve_case()
        if not solved:
            hour_status.append({
                "time": t,
                "status": "blown_up",
                "detail": "N0 did not converge"
            })
            continue

        # -------------------------
        # Pre-ACCOR metrics
        # -------------------------
        max_loading_pre, thermal_pre, voltage_pre = get_metrics()

        n0_summary.append({
            "time": t,
            "solve_mode_pre": solve_mode_pre,
            "max_loading_pre": round(max_loading_pre, 2),
            "thermal_viol_pre": len(thermal_pre),
            "voltage_viol_pre": len(voltage_pre)
        })

        thermal_pre_all += [{"time": t, **x} for x in thermal_pre]
        voltage_pre_all += [{"time": t, **x} for x in voltage_pre]

        pre = machine_snapshot()

        # -------------------------
        # Only run ACCOR if there is thermal violation
        # -------------------------
        if len(thermal_pre) == 0:
            post_accor_summary.append({
                "time": t,
                "accor_ran": False,
                "accor_success": None,
                "accor_stage": "skipped_no_thermal",
                "accor_ierr": None,
                "solve_mode_post": None,
                "max_loading_post": round(max_loading_pre, 2),
                "thermal_viol_post": len(thermal_pre),
                "voltage_viol_post": len(voltage_pre)
            })

            accor_debug.append({
                "time": t,
                "report_file": None,
                "progress_file": None,
                "alert_file": None,
                "prompt_file": None,
                "summary_file": None,
                "dfax_ierr": None,
                "accor_ierr": None,
                "accor_ierr_text": None,
                "generators_changed": 0
            })

            hour_status.append({
                "time": t,
                "status": "solved_no_accor_needed",
                "detail": "N0 solved; no thermal violation; solve_mode={}".format(solve_mode_pre)
            })
            continue

        # -------------------------
        # Run ACCOR
        # -------------------------
        accor_success, accor_stage, accor_ierr, logs, dfax_ierr = run_accor(t)

        if not accor_success:
            write_debug_summary(
                logs["summary"],
                t=t,
                dfax_ierr=dfax_ierr,
                accor_ierr=accor_ierr,
                thermal_pre_count=len(thermal_pre),
                voltage_pre_count=len(voltage_pre),
                thermal_post_count=None,
                voltage_post_count=None,
                generators_changed=0,
                solve_mode_pre=solve_mode_pre,
                solve_mode_post=None
            )

            post_accor_summary.append({
                "time": t,
                "accor_ran": True,
                "accor_success": False,
                "accor_stage": accor_stage,
                "accor_ierr": accor_ierr,
                "solve_mode_post": None,
                "max_loading_post": None,
                "thermal_viol_post": None,
                "voltage_viol_post": None
            })

            accor_debug.append({
                "time": t,
                "report_file": logs["report"],
                "progress_file": logs["progress"],
                "alert_file": logs["alert"],
                "prompt_file": logs["prompt"],
                "summary_file": logs["summary"],
                "dfax_ierr": dfax_ierr,
                "accor_ierr": accor_ierr,
                "accor_ierr_text": accor_ierr_text(accor_ierr),
                "generators_changed": 0
            })

            hour_status.append({
                "time": t,
                "status": accor_stage,
                "detail": "{}; ierr={} ({})".format(
                    accor_stage, accor_ierr, accor_ierr_text(accor_ierr)
                )
            })
            continue

        # -------------------------
        # Solve after ACCOR
        # -------------------------
        post_solved, solve_mode_post = solve_case()
        if not post_solved:
            write_debug_summary(
                logs["summary"],
                t=t,
                dfax_ierr=dfax_ierr,
                accor_ierr=0,
                thermal_pre_count=len(thermal_pre),
                voltage_pre_count=len(voltage_pre),
                thermal_post_count=None,
                voltage_post_count=None,
                generators_changed=0,
                solve_mode_pre=solve_mode_pre,
                solve_mode_post=solve_mode_post
            )

            post_accor_summary.append({
                "time": t,
                "accor_ran": True,
                "accor_success": True,
                "accor_stage": "post_accor_blown_up",
                "accor_ierr": 0,
                "solve_mode_post": solve_mode_post,
                "max_loading_post": None,
                "thermal_viol_post": None,
                "voltage_viol_post": None
            })

            accor_debug.append({
                "time": t,
                "report_file": logs["report"],
                "progress_file": logs["progress"],
                "alert_file": logs["alert"],
                "prompt_file": logs["prompt"],
                "summary_file": logs["summary"],
                "dfax_ierr": dfax_ierr,
                "accor_ierr": 0,
                "accor_ierr_text": "no error occurred",
                "generators_changed": 0
            })

            hour_status.append({
                "time": t,
                "status": "post_accor_blown_up",
                "detail": "post-ACCOR solve failed; solve_mode={}".format(solve_mode_post)
            })
            continue

        # -------------------------
        # Post-ACCOR metrics
        # -------------------------
        max_loading_post, thermal_post, voltage_post = get_metrics()

        post_accor_summary.append({
            "time": t,
            "accor_ran": True,
            "accor_success": True,
            "accor_stage": "accor_completed",
            "accor_ierr": 0,
            "solve_mode_post": solve_mode_post,
            "max_loading_post": round(max_loading_post, 2),
            "thermal_viol_post": len(thermal_post),
            "voltage_viol_post": len(voltage_post)
        })

        thermal_post_all += [{"time": t, **x} for x in thermal_post]
        voltage_post_all += [{"time": t, **x} for x in voltage_post]

        # -------------------------
        # Compare generator outputs
        # -------------------------
        post = machine_snapshot()
        generators_changed = 0

        for k, p0 in pre.items():
            p1 = post.get(k, 0.0)
            delta = p0 - p1

            if abs(delta) > 0.01:
                generators_changed += 1

            if delta > 0.1:
                bus_str, id_str = k.split("_", 1)
                curtailment.append({
                    "time": t,
                    "asset_group": gen_name_map.get(k, ""),
                    "bus": int(bus_str),
                    "id": id_str,
                    "pgen_pre": round(p0, 2),
                    "pgen_post": round(p1, 2),
                    "curtail_mw": round(delta, 2)
                })

        write_debug_summary(
            logs["summary"],
            t=t,
            dfax_ierr=dfax_ierr,
            accor_ierr=0,
            thermal_pre_count=len(thermal_pre),
            voltage_pre_count=len(voltage_pre),
            thermal_post_count=len(thermal_post),
            voltage_post_count=len(voltage_post),
            generators_changed=generators_changed,
            solve_mode_pre=solve_mode_pre,
            solve_mode_post=solve_mode_post
        )

        accor_debug.append({
            "time": t,
            "report_file": logs["report"],
            "progress_file": logs["progress"],
            "alert_file": logs["alert"],
            "prompt_file": logs["prompt"],
            "summary_file": logs["summary"],
            "dfax_ierr": dfax_ierr,
            "accor_ierr": 0,
            "accor_ierr_text": "no error occurred",
            "generators_changed": generators_changed
        })

        if generators_changed == 0:
            hour_status.append({
                "time": t,
                "status": "accor_no_action",
                "detail": (
                    "ACCOR ierr=0 but no generator PGEN changed; "
                    "thermal_pre={}, thermal_post={}".format(len(thermal_pre), len(thermal_post))
                )
            })
        else:
            hour_status.append({
                "time": t,
                "status": "solved_accor_completed",
                "detail": (
                    "N0 solved, ACCOR completed, solve_mode_pre={}, solve_mode_post={}, "
                    "thermal_pre={}, thermal_post={}, generators_changed={}".format(
                        solve_mode_pre, solve_mode_post,
                        len(thermal_pre), len(thermal_post), generators_changed
                    )
                )
            })

    # =========================================================
    # 10. SAVE RESULTS
    # =========================================================
    save_csv(
        n0_summary,
        "n0_summary.csv",
        ["time", "solve_mode_pre", "max_loading_pre", "thermal_viol_pre", "voltage_viol_pre"]
    )

    save_csv(
        post_accor_summary,
        "post_accor_summary.csv",
        [
            "time", "accor_ran", "accor_success", "accor_stage", "accor_ierr",
            "solve_mode_post", "max_loading_post", "thermal_viol_post", "voltage_viol_post"
        ]
    )

    save_csv(
        thermal_pre_all,
        "thermal_violations_pre_accor.csv",
        ["time", "branch", "ckt", "pct"]
    )

    save_csv(
        voltage_pre_all,
        "voltage_violations_pre_accor.csv",
        ["time", "bus", "pu"]
    )

    save_csv(
        thermal_post_all,
        "thermal_violations_post_accor.csv",
        ["time", "branch", "ckt", "pct"]
    )

    save_csv(
        voltage_post_all,
        "voltage_violations_post_accor.csv",
        ["time", "bus", "pu"]
    )

    save_csv(
        curtailment,
        "curtailment.csv",
        ["time", "asset_group", "bus", "id", "pgen_pre", "pgen_post", "curtail_mw"]
    )

    save_csv(
        accor_debug,
        "accor_debug.csv",
        [
            "time",
            "report_file",
            "progress_file",
            "alert_file",
            "prompt_file",
            "summary_file",
            "dfax_ierr",
            "accor_ierr",
            "accor_ierr_text",
            "generators_changed"
        ]
    )

    save_csv(
        hour_status,
        "hour_status.csv",
        ["time", "status", "detail"]
    )

    final_print("\nALL RESULTS SAVED")
    final_print("Check these files:")
    final_print("  n0_summary.csv")
    final_print("  post_accor_summary.csv")
    final_print("  thermal_violations_pre_accor.csv")
    final_print("  thermal_violations_post_accor.csv")
    final_print("  voltage_violations_pre_accor.csv")
    final_print("  voltage_violations_post_accor.csv")
    final_print("  curtailment.csv")
    final_print("  accor_debug.csv")
    final_print("  hour_status.csv")
    final_print("  accor_report_YYYYMMDD_HHMM.txt")
    final_print("  accor_progress_YYYYMMDD_HHMM.txt")
    final_print("  accor_alert_YYYYMMDD_HHMM.txt")
    final_print("  accor_prompt_YYYYMMDD_HHMM.txt")
    final_print("  accor_debug_summary_YYYYMMDD_HHMM.txt")

if __name__ == "__main__":
    main()