# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mPGYmk_FHuvoBn79i_Rc85Eksm6bHH5h
"""

# -*- coding: utf-8 -*-
import os
import math
import pandas as pd
import psspy

psspy.psseinit(200000)
psspy.report_output(6, "", [])
psspy.progress_output(6, "", [])
psspy.alert_output(6, "", [])
psspy.prompt_output(6, "", [])
psspy.lines_per_page_one_device(1, 1000000)

PROJECT_PATH = r"C:\Users\tanbir.rahman\Documents\PTI\PSSE35\EXAMPLE\Projects"
os.chdir(PROJECT_PATH)

BASE_CASE = os.path.join(PROJECT_PATH, "2021RC_2025SP_South-High_Tie-Econ_Solar-0.95_p.sav")
LOAD_CSV  = os.path.join(PROJECT_PATH, "load_clean.csv") #Load_Dispatch.csv
GEN_CSV   = os.path.join(PROJECT_PATH, "gen_clean.csv")  #Generation_Dispatch.csv
GEN_MAP   = os.path.join(PROJECT_PATH, "gen_map_clean.csv") #Gen_map.csv

CON_FILE  = os.path.join(PROJECT_PATH, "SE_Contingencies.con")
MON_FILE  = os.path.join(PROJECT_PATH, "study.mon")
SUB_FILE  = os.path.join(PROJECT_PATH, "study.sub")
DFX_FILE  = os.path.join(PROJECT_PATH, "brooks_area.dfx")

STUDY_HOURS = 8760
V_MIN, V_MAX = 0.95, 1.05
THERMAL_LIMIT = 100.0
GEN_CTRL_LABEL = "ALL_ALBERTA"

ACCOR_OPTIONS = [0,0,0,0,0,1,1,1,1,0,0,0,0,0]
ACCOR_VALUES  = [0.5,100.0,0.1,0.1,1,1,1,1,1,1]

def fmt_id(x):
    return str(x).strip().ljust(2)

def save_csv(data, path, cols):
    df = pd.DataFrame(data)
    if df.empty:
        df = pd.DataFrame(columns=cols)
    else:
        for c in cols:
            if c not in df.columns:
                df[c] = None
        df = df[cols]
    if "time" in df.columns:
        df["time"] = pd.to_datetime(df["time"]).dt.strftime("%Y-%m-%d %H:%M:%S")
    try:
        df.to_csv(path, index=False)
    except PermissionError:
        df.to_csv(path.replace(".csv", "_new.csv"), index=False)

def solve_case():
    for mode, args in [
        ("flat_start_nr", [1,0,0,1,1,0,99,0]),
        ("normal_nr",     [0,0,0,1,1,0,99,0]),
        ("gauss",         None),
        ("nr_after_gauss",[0,0,0,1,1,1,99,0]),
    ]:
        try:
            ierr = psspy.mslv() if args is None else psspy.fnsl(args)
            if ierr == 0 and psspy.solved() == 0:
                return True, mode
        except:
            pass
    return False, "failed"

def machine_snapshot():
    ierr1, bus = psspy.amachint(-1, 4, "NUMBER")
    ierr2, mid = psspy.amachchar(-1, 4, "ID")
    ierr3, pgen = psspy.amachreal(-1, 4, "PGEN")
    snap = {}
    if ierr1 == 0 and ierr2 == 0 and ierr3 == 0:
        for b, i, p in zip(bus[0], mid[0], pgen[0]):
            snap[f"{b}_{i.strip()}"] = p
    return snap

def get_machine_name_map():
    gm = pd.read_csv(GEN_MAP)
    out = {}
    if {"bus", "id", "asset_group"}.issubset(gm.columns):
        for _, r in gm.iterrows():
            out[f"{int(r['bus'])}_{str(r['id']).strip()}"] = str(r["asset_group"]).strip()
    return out

def load_data():
    ld = pd.read_csv(LOAD_CSV).rename(columns={
        "DT_MST": "datetime", "Bus Number": "bus", "Id": "id",
        "P_MW": "p_mw", "Q_Mvar": "q_mvar"
    })
    gd = pd.read_csv(GEN_CSV).rename(columns={
        "DT_MST": "datetime", "MW": "mw"
    })
    gm = pd.read_csv(GEN_MAP)

    ld["datetime"] = pd.to_datetime(ld["datetime"]).dt.floor("h")
    gd["datetime"] = pd.to_datetime(gd["datetime"]).dt.floor("h")
    gd["asset_group"] = gd["asset_group"].astype(str).str.upper().str.strip()
    gm["asset_group"] = gm["asset_group"].astype(str).str.upper().str.strip()
    return ld, gd, gm

def apply_dispatch(t, ld, gd, gm):
    hr_ld = ld[ld["datetime"] == t]
    for _, r in hr_ld.iterrows():
        psspy.load_chng_5(
            int(r["bus"]), fmt_id(r["id"]),
            realar1=float(r["p_mw"]), realar2=float(r["q_mvar"])
        )

    hr_gn = gd[gd["datetime"] == t]
    for _, r in hr_gn.iterrows():
        mw = float(r["mw"])
        if mw <= 0.01:
            continue
        units = gm[gm["asset_group"] == str(r["asset_group"]).upper().strip()]
        if not units.empty:
            share = mw / len(units)
            for _, u in units.iterrows():
                psspy.machine_chng_2(int(u["bus"]), fmt_id(u["id"]), realar1=share)

def get_metrics():
    thermal, voltage = [], []
    max_loading = 0.0

    ierr1, data = psspy.abrnreal(-1, 0, 0, 1, 1, ["P", "Q", "RATEA"])
    ierr2, ids  = psspy.abrnchar(-1, 0, 0, 1, 1, ["ID"])
    ierr3, buses = psspy.abrnint(-1, 0, 0, 1, 1, ["FROMNUMBER", "TONUMBER"])

    if ierr1 == 0 and ierr2 == 0 and ierr3 == 0:
        for u, v, c, p, q, r in zip(buses[0], buses[1], ids[0], data[0], data[1], data[2]):
            mva = math.sqrt(p**2 + q**2)
            pct = (mva / r) * 100.0 if r > 0 else 0.0
            max_loading = max(max_loading, pct)
            if pct > THERMAL_LIMIT:
                thermal.append({"branch": f"{u}-{v}", "ckt": c.strip(), "pct": round(pct, 2)})

    ierr4, b = psspy.abusint(-1, 2, "NUMBER")
    ierr5, v = psspy.abusreal(-1, 2, "PU")
    if ierr4 == 0 and ierr5 == 0:
        for bus, pu in zip(b[0], v[0]):
            if pu < V_MIN or pu > V_MAX:
                voltage.append({"bus": bus, "pu": round(pu, 4)})

    return max_loading, thermal, voltage

def run_accor():
    ierr_dfax = psspy.dfax_2([1, 1, 0], SUB_FILE, MON_FILE, CON_FILE, DFX_FILE)
    if ierr_dfax != 0:
        return False, "dfax_failed", ierr_dfax
    ierr_accor = psspy.accor_3(ACCOR_OPTIONS, ACCOR_VALUES, [GEN_CTRL_LABEL, "", "", "", "", ""], DFX_FILE)
    if ierr_accor != 0:
        return False, "accor_failed", ierr_accor
    return True, "accor_ok", 0

def main():
    ld, gd, gm = load_data()
    times = sorted(gd["datetime"].unique())[:STUDY_HOURS]
    gen_name_map = get_machine_name_map()

    n0_summary, post_accor_summary = [], []
    thermal_all, voltage_all = [], []
    post_thermal_all, post_voltage_all = [], []
    curtailment, hour_status = [], []

    for t in times:
        ierr_case = psspy.case(BASE_CASE)
        if ierr_case != 0:
            hour_status.append({"time": t, "status": "case_load_failed", "detail": f"case ierr={ierr_case}"})
            continue

        try:
            apply_dispatch(t, ld, gd, gm)
        except Exception as e:
            hour_status.append({"time": t, "status": "dispatch_failed", "detail": str(e)})
            continue

        solved, solve_mode = solve_case()
        if not solved:
            hour_status.append({"time": t, "status": "blown_up", "detail": "N0 did not converge"})
            continue

        max_loading_pre, thermal_pre, voltage_pre = get_metrics()
        n0_summary.append({
            "time": t,
            "solve_mode_pre": solve_mode,
            "max_loading_pre": round(max_loading_pre, 2),
            "thermal_viol_pre": len(thermal_pre),
            "voltage_viol_pre": len(voltage_pre)
        })
        thermal_all += [{"time": t, **x} for x in thermal_pre]
        voltage_all += [{"time": t, **x} for x in voltage_pre]

        pre = machine_snapshot()

        if not thermal_pre:
            post_accor_summary.append({
                "time": t,
                "accor_ran": False,
                "accor_success": None,
                "accor_stage": "skipped_no_thermal",
                "accor_ierr": None,
                "solve_mode_post": None,
                "max_loading_post": round(max_loading_pre, 2),
                "thermal_viol_post": len(thermal_pre),
                "voltage_viol_post": len(voltage_pre)
            })
            hour_status.append({"time": t, "status": "solved_no_accor_needed", "detail": solve_mode})
            continue

        accor_success, accor_stage, accor_ierr = run_accor()
        if not accor_success:
            post_accor_summary.append({
                "time": t,
                "accor_ran": True,
                "accor_success": False,
                "accor_stage": accor_stage,
                "accor_ierr": accor_ierr,
                "solve_mode_post": None,
                "max_loading_post": None,
                "thermal_viol_post": None,
                "voltage_viol_post": None
            })
            hour_status.append({"time": t, "status": accor_stage, "detail": f"ierr={accor_ierr}"})
            continue

        post_solved, post_solve_mode = solve_case()
        if not post_solved:
            post_accor_summary.append({
                "time": t,
                "accor_ran": True,
                "accor_success": True,
                "accor_stage": "post_accor_blown_up",
                "accor_ierr": 0,
                "solve_mode_post": post_solve_mode,
                "max_loading_post": None,
                "thermal_viol_post": None,
                "voltage_viol_post": None
            })
            hour_status.append({"time": t, "status": "post_accor_blown_up", "detail": post_solve_mode})
            continue

        max_loading_post, thermal_post, voltage_post = get_metrics()
        post_accor_summary.append({
            "time": t,
            "accor_ran": True,
            "accor_success": True,
            "accor_stage": "accor_completed",
            "accor_ierr": 0,
            "solve_mode_post": post_solve_mode,
            "max_loading_post": round(max_loading_post, 2),
            "thermal_viol_post": len(thermal_post),
            "voltage_viol_post": len(voltage_post)
        })

        post_thermal_all += [{"time": t, **x} for x in thermal_post]
        post_voltage_all += [{"time": t, **x} for x in voltage_post]

        post = machine_snapshot()
        for k, p0 in pre.items():
            p1 = post.get(k, 0.0)
            delta = p0 - p1
            if delta > 0.1:
                bus_str, id_str = k.split("_", 1)
                curtailment.append({
                    "time": t,
                    "asset_group": gen_name_map.get(k, ""),
                    "bus": int(bus_str),
                    "id": id_str,
                    "pgen_pre": round(p0, 2),
                    "pgen_post": round(p1, 2),
                    "curtail_mw": round(delta, 2)
                })

        hour_status.append({"time": t, "status": "solved_accor_completed", "detail": ""})

    save_csv(n0_summary, "n0_summary.csv",
             ["time", "solve_mode_pre", "max_loading_pre", "thermal_viol_pre", "voltage_viol_pre"])

    save_csv(post_accor_summary, "post_accor_summary.csv",
             ["time", "accor_ran", "accor_success", "accor_stage", "accor_ierr",
              "solve_mode_post", "max_loading_post", "thermal_viol_post", "voltage_viol_post"])

    save_csv(thermal_all, "thermal_violations_pre_accor.csv", ["time", "branch", "ckt", "pct"])
    save_csv(voltage_all, "voltage_violations_pre_accor.csv", ["time", "bus", "pu"])
    save_csv(post_thermal_all, "thermal_violations_post_accor.csv", ["time", "branch", "ckt", "pct"])
    save_csv(post_voltage_all, "voltage_violations_post_accor.csv", ["time", "bus", "pu"])
    save_csv(curtailment, "curtailment.csv",
             ["time", "asset_group", "bus", "id", "pgen_pre", "pgen_post", "curtail_mw"])
    save_csv(hour_status, "hour_status.csv", ["time", "status", "detail"])

if __name__ == "__main__":
    main()